require:
    - rubocop-rake
    - rubocop-rspec # for generated projects

AllCops:
    Exclude:
        - 'test/tmp/*/sample/Gemfile'
        - 'test/fixtures/**/*'
        - 'vendor/bundle/**/*'
    NewCops: enable
    TargetRubyVersion: 2.6

Layout/LineLength:
    Max: 90

Layout/SpaceAroundEqualsInParameterDefault:
    EnforcedStyle: no_space

Metrics/BlockLength:
      IgnoredMethods:
        - run_hoboken

Metrics/ClassLength:
    Max: 150

Metrics/MethodLength:
    Max: 15

RSpec/DescribeClass:
    Enabled: false

RSpec/MultipleDescribes:
    Enabled: false

Style/BlockDelimiters:
    EnforcedStyle: braces_for_chaining

Style/YodaCondition:
    EnforcedStyle: require_for_equality_operators_only
