#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'

APP_ROOT = File.expand_path('..', __dir__)

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

FileUtils.chdir APP_ROOT do
  puts '== Starting application console =='
  system! 'bundle exec racksh'
end
