#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'

APP_ROOT = File.expand_path('..', __dir__)

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

FileUtils.chdir APP_ROOT do
  puts '== Starting application console =='
  puts 'Console supports racksh. A `$rack` global variable is provided for'
  puts "making simulated requests (i.e. `$rack.get '/'`)."
  puts "\nSee the racksh gem for more details."
  puts "https://github.com/sickill/racksh\n\n"
  system! 'bundle exec racksh'
end
