#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'

APP_ROOT = File.expand_path('..', __dir__)

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

FileUtils.chdir APP_ROOT do
  # This script is a way to set up or update your development environment
  # automatically. This script is idempotent, so that you can run it at
  # anytime and get an expectable outcome. Add necessary setup steps to
  # this file.

  puts '== Installing dependencies =='
  system! 'gem install bundler --conservative'
  system! 'bundle config --local cache_all true'
  system! 'bundle config --local cache_all_platforms true'
  system! 'bundle config --local ignore_messages.rpush true'
  system('bundle check') || system!('bundle install')

  system! 'gem list "^foreman$" -v 0.87.2 -i --silent || gem install foreman'
  system! 'gem list "^rerun$" -v 0.13.1 -i --silent || gem install rerun'
  system! 'gem list "^rb-fsevent$" -v 0.11.0 -i --silent || gem install rb-fsevent'
end
